name: script

on:
  schedule:
    - cron: '0 * * * *'  # This will run the job every hour

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.5"
        
    - name: Install dependencies
      run: |
        pip install httpx pandas

    - name: Run script
      run: python fetch_vertex_data.py


  

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv 
        git commit -m "Add updated CSVs" || echo "No changes to commit"

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
